SEED: 7

MODEL:
  TYPE: 'unet' # should support unet, unet_lstm, siammese_conc, siamese_diff,
  OUT_CHANNELS: 1
  IN_CHANNELS: 2
  LOSS_TYPE: 'FrankensteinLoss'

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True

DATASET:
  PATH: 'C:/Users/shafner/urban_change_detection/OSCD_dataset/preprocessed/'
  MODE: 'optical' # optical, radar or fusion
  SENTINEL1:
    BANDS: ['VV', 'VH']
    TEMPORAL_MODE: 'bi-temporal'
  SENTINEL2:
    BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']
    TEMPORAL_MODE: 'bi-temporal'
  ALL_CITIES: ['abudhabi', 'aguasclaras', 'beihai', 'beirut', 'bercy', 'bordeaux', 'cupertino', 'hongkong', 'lasvegas',
               'mumbai', 'nantes', 'paris', 'pisa', 'rennes', 'saclay_e']
  TEST_CITIES: ['abudhabi']

OUTPUT_BASE_DIR: '/storage/shafner/urban_change_detection/run_logs/'

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 2
  EPOCHS: 50

AUGMENTATION:
  CROP_TYPE: 'uniform' # uniform or importance
  CROP_SIZE: 64
  RANDOM_FLIP: True
  RANDOM_ROTATE: True