SEED: 7
DEBUG: False
SAVE_MODEL: False

MODEL:
  TYPE: 'unet' # should support unet, unet_lstm, siammese_conc, siamese_diff,
  TOPOLOGY: [64, 128, 256, 512,]
  OUT_CHANNELS: 1
  IN_CHANNELS: 2
  LOSS_TYPE: 'FrankensteinLoss'
  NEGATIVE_WEIGHT: 0.2
  POSITIVE_WEIGHT: 0.8

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True

DATASET:
  PATH: '/storage/shafner/urban_change_detection/OSCD_dataset/preprocessed/'
  MODE: 'optical' # optical, radar or fusion
  SENTINEL1:
    BANDS: ['VV', 'VH']
    TEMPORAL_MODE: 'bi-temporal'
  SENTINEL2:
    BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']
    TEMPORAL_MODE: 'bi-temporal'
  TRAIN: ['aguasclaras', 'bercy', 'bordeaux', 'nantes', 'paris', 'rennes', 'saclay_e', 'abudhabi', 'cupertino',
                'pisa', 'beihai', 'hongkong', 'beirut', 'mumbai']
  TEST: ['brasilia', 'montpellier', 'norcia', 'rio', 'saclay_w', 'valencia', 'dubai', 'lasvegas', 'milano',
        'chongqing']

OUTPUT_BASE_DIR: '/storage/shafner/urban_change_detection/run_logs/'

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 4
  EPOCHS: 400

AUGMENTATION:
  CROP_TYPE: 'importance' # uniform or importance
  CROP_SIZE: 32
  RANDOM_FLIP: True
  RANDOM_ROTATE: True