SEED: 7

MODEL:
  TYPE: 'unet' # should support unet, unet_lstm, siammese_conc, siamese_diff,
  BINARY_CLASSIFICATION: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 2
  LOSS_TYPE: 'FrankensteinLoss'

DATALOADER:
  NUM_WORKER: 8
  SHUFFLE: True
  SENTINEL1:
    BANDS: ['VV', 'VH']
    TEMPORAL_MODE: 'bi-temporal'
  SENTINEL2:
    BANDS: ['B2', 'B3', 'B4', 'B8', 'B11', 'B12']
    TEMPORAL_MODE: 'bi-temporal'

DATASETS:
  TRAIN: '/storage/shafner/urban_change_detection/Onera/'
  TEST: '/storage/shafner/urban_change_detection/Onera/'

OUTPUT_BASE_DIR: '/storage/shafner/urban_change_detection/run_logs/'

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 16
  EPOCHS: 50

AUGMENTATION:
  CROP_TYPE: 'none' # importance or none
  CROP_SIZE: 1024
  RANDOM_FLIP: True
  RANDOM_ROTATE: True