_BASE_: "base.yaml"

SEED: 9
SAVE_MODEL: False
DEBUG: False

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 26
  LOSS_TYPE: 'BCEWithLogitsLoss'

DATASET:
  MODE: 'optical'
  SENTINEL1_BANDS: ['VV']
  SENTINEL2_BANDS: ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']
  LOAD_INTO_MEMORY: True