_BASE_: "base.yaml"

SEED: 1
SAVE_MODEL: True
DEBUG: True

MODEL:
  TYPE: 'unet'
  IN_CHANNELS: 26

DATASET:
  PATH: '/storage/shafner/urban_change_detection/OSCD_dataset/preprocessed/'
  MODE: 'optical'
  SENTINEL2_BANDS: ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']

DATALOADER:
  NUM_WORKERS: 16

TRAINER:
  LR: 1e-5
  EPOCHS: 10
  BATCH_SIZE: 32